apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotdep #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the application container
  selector:
    matchLabels:
      app: dotapp
  template:
    metadata:
      labels:
        app: dotapp 
    spec:
      containers:
      - name: dotapp #The name of the application container
        image: preethi00/dotnetapp:tagname #The Docker image for building the application container
        ports:
        - containerPort: 80 #The port for the application   container
